server:
    port: 8088
spring:
    application:
        name: ms1
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: ''
        url: jdbc:mysql://localhost:3306/jjs?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: 110492365213-n4hm0juabfuroqi9cbs27jgudssuq270.apps.googleusercontent.com
                        client-secret: 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
                        scope: profile,email
                    kakao:
                        client-id: d5367acce2be30584d6688b363e45e24
                        redirect-uri: 'http://localhost:8088/login/oauth2/code/{registrationId}'
                        authorization-grant-type: authorization_code
                    naver:
                        client-id: 4gijZmdql3geSs9BmBty
                        client-secret: yh8rinsnCu
                        redirect-uri: 'http://localhost:8088/login/oauth2/code/{registrationId}'
                        authorization-grant-type: authorization_code


                provider:
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-name-attribute: id
                    naver:
                        authorization-uri: https://nid.naver.com/oauth2.0/authorize
                        token-uri: https://nid.naver.com/oauth2.0/token
                        user-info-uri: https://openapi.naver.com/v1/nid/me
                        user-name-attribute: response